-- %d/%m/%Y
show columns from clientes;

-- CONSULTAS BÁSICAS
SELECT NOMBREARTICULO, SECCION, PRECIO FROM PRODUCTOS WHERE SECCION = 'CERAMICA' OR SECCION = 'DEPORTES';
SELECT * FROM PRODUCTOS WHERE SECCION = 'DEPORTES' AND PAISDEORIGEN = 'USA';
SELECT * FROM PRODUCTOS WHERE FECHA BETWEEN '2000-03-01' AND '2000-04-30';
SELECT * FROM PRODUCTOS WHERE YEAR(FECHA) = 2000 AND MONTH(FECHA) BETWEEN 3 AND 4;
SELECT * FROM PRODUCTOS WHERE PAISDEORIGEN != 'ESPANA';

-- ORDENAMIENTO
SELECT * FROM PRODUCTOS WHERE PRECIO > 100 ORDER BY PRECIO DESC;
SELECT * FROM PRODUCTOS WHERE PRECIO > 100 ORDER BY SECCION DESC, PRECIO ;

-- CONSULTAS DE AGRUPACIÓN
-- campo de agrupación y campo de cálculo
SELECT SECCION, SUM(PRECIO) AS TOTAL FROM PRODUCTOS GROUP BY SECCION ORDER BY TOTAL;
-- HAVING: sustituo del WHERE en consultas de agrupación
-- count() no cuenta registros en blanco
SELECT SECCION, AVG(PRECIO) AS MEDIA FROM PRODUCTOS GROUP BY SECCION HAVING SECCION = 'DEPORTES' OR SECCION='CONFECCION';
SELECT POBLACION, COUNT(CODIGOCLIENTE) AS TOTAL FROM CLIENTES GROUP BY POBLACION ORDER BY TOTAL;
-- dos formas distintas, mismo resultado
SELECT SECCION, MAX(PRECIO) AS ALTO FROM PRODUCTOS GROUP BY SECCION HAVING SECCION='CONFECCION';
SELECT SECCION, MAX(PRECIO) AS ALTO FROM PRODUCTOS WHERE SECCION='CONFECCION';
-- consulta con resultado erroneo
-- el NOMBREARTICULO NO coincide con el precio más alto
SELECT NOMBREARTICULO, SECCION, MAX(PRECIO) AS ALTO FROM PRODUCTOS WHERE SECCION='CONFECCION';

-- CONSULTAS DE CÁLCULO
-- campos nuevos
SELECT NOMBREARTICULO, SECCION, PRECIO, ROUND(PRECIO*1.19,2) AS CON_IVA FROM PRODUCTOS;
SELECT NOMBREARTICULO, SECCION, PRECIO, DATEDIFF(NOW(),FECHA) AS 'HACE X DIAS' FROM PRODUCTOS WHERE SECCION = 'DEPORTES';