-- CONSULTAS DE ACCIÓN
-- modifican la información de las tablas


-- ACTUALIZACIÓN
-- actualizar información de las tablas
UPDATE PRODUCTOS SET PRECIO=PRECIO+10 WHERE SECCION='DEPORTES';
UPDATE PRODUCTOS SET SECCION='DEPORTIVOS' WHERE SECCION='DEPORTES';

-- CREACIÓN DE TABLA
-- crea una tabla a partir de una consulta
CREATE TABLE CLIENTES_MADRID SELECT * FROM CLIENTES WHERE POBLACION='MADRID';

-- ELIMINACIÓN
-- eliminar a partir de una consulta
DELETE FROM CLIENTES WHERE POBLACION='MADRID' AND PRECIO BETWEEN 50 AND 100;

-- DATOS ANEXADOS
-- añadir datos a una tabla a partir de una consulta
INSERT INTO PRODUCTOS SELECT * FROM PRODUCTOSNUEVOS;
