-- PROCEDIMIENETOS ALMACENADOS

CREATE PROCEDURE CLIENTESMADRID() SELECT * FROM CLIENTES WHERE POBLACION='MADRID';
DROP PROCEDURE CLIENTESMADRID;
CALL CLIENTESMADRID();

CREATE PROCEDURE UPDATEPRODUCT(PRECIONUEVO DOUBLE, CODIGO VARCHAR(4))
	UPDATE PRODUCTOS SET PRECIO = PRECIONUEVO WHERE CODIGOARTICULO=CODIGO;
CALL UPDATEPRODUCT(6.63,'AR01');
SELECT PRECIO FROM PRODUCTOS WHERE CODIGOARTICULO='AR01';


-- delimitador de bloque $$
DELIMITER $$
	CREATE PROCEDURE CALCULA_EDAD(ANO_NACIMIENTO INT)
	BEGIN
	DECLARE ANO_ACTUAL INT DEFAULT YEAR(NOW());
	DECLARE EDAD INT;
	SET EDAD=ANO_ACTUAL-ANO_NACIMIENTO;
	SELECT EDAD; 			-- equivale al return
	END$$ 					-- fin del bloque
DELIMITER ; 				
-- reseteo del delimitador de bloque $$
DROP PROCEDURE CALCULA_EDAD;
CALL CALCULA_EDAD(1995);

