#VISTAS
-- Privacidad de la información.
-- Optimización en consutas a la BBDD.
-- Ofrece entornos de pruebas.

-- Las vistas reflejan la información real
-- si cambia algo en una tabla, la vista lo nota

CREATE VIEW ARTICULOS_DEPORTES AS SELECT CODIGOARTICULO, NOMBREARTICULO, SECCION, PRECIO, FECHA FROM PRODUCTOS WHERE SECCION='DEPORTES';
DROP VIEW IF EXISTS ARTICULOS_DEPORTES;
SELECT CODIGOARTICULO, NOMBREARTICULO, SECCION, PRECIO, FECHA FROM PRODUCTOS WHERE SECCION='DEPORTES';
SELECT * FROM ARTICULOS_DEPORTES;

ALTER VIEW ARTICULOS_DEPORTES AS SELECT CODIGOARTICULO, NOMBREARTICULO, SECCION, PRECIO FROM PRODUCTOS WHERE SECCION='DEPORTES';
