insert into trenes (modelo, capacidad) values ('Elise', 1);
insert into trenes (modelo, capacidad) values ('Outback', 2);
insert into trenes (modelo, capacidad) values ('Civic', 3);
insert into trenes (modelo, capacidad) values ('Topaz', 4);
insert into trenes (modelo, capacidad) values ('Rapide', 5);
insert into trenes (modelo, capacidad) values ('Grand Voyager', 6);
insert into trenes (modelo, capacidad) values ('Sportvan G30', 7);
insert into trenes (modelo, capacidad) values ('Nitro', 8);
insert into trenes (modelo, capacidad) values ('LS', 9);
insert into trenes (modelo, capacidad) values ('Pajero', 10);
insert into trenes (modelo, capacidad) values ('Rally Wagon 3500', 11);
insert into trenes (modelo, capacidad) values ('Sierra 3500', 12);
insert into trenes (modelo, capacidad) values ('Intrepid', 13);
insert into trenes (modelo, capacidad) values ('Jimmy', 14);
insert into trenes (modelo, capacidad) values ('SC', 15);
insert into trenes (modelo, capacidad) values ('Econoline E250', 16);
insert into trenes (modelo, capacidad) values ('S8', 17);
insert into trenes (modelo, capacidad) values ('Supra', 18);
insert into trenes (modelo, capacidad) values ('A8', 19);
insert into trenes (modelo, capacidad) values ('Eurovan', 20);
insert into trenes (modelo, capacidad) values ('8 Series', 21);
insert into trenes (modelo, capacidad) values ('XLR', 22);
insert into trenes (modelo, capacidad) values ('Titan', 23);
insert into trenes (modelo, capacidad) values ('E250', 24);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 25);
insert into trenes (modelo, capacidad) values ('5 Series', 26);
insert into trenes (modelo, capacidad) values ('Envoy', 27);
insert into trenes (modelo, capacidad) values ('Hearse', 28);
insert into trenes (modelo, capacidad) values ('Avalanche', 29);
insert into trenes (modelo, capacidad) values ('CL-Class', 30);
insert into trenes (modelo, capacidad) values ('Escalade', 31);
insert into trenes (modelo, capacidad) values ('Protege5', 32);
insert into trenes (modelo, capacidad) values ('MDX', 33);
insert into trenes (modelo, capacidad) values ('Mirage', 34);
insert into trenes (modelo, capacidad) values ('Silhouette', 35);
insert into trenes (modelo, capacidad) values ('M-Class', 36);
insert into trenes (modelo, capacidad) values ('9-3', 37);
insert into trenes (modelo, capacidad) values ('Diamante', 38);
insert into trenes (modelo, capacidad) values ('TrailBlazer', 39);
insert into trenes (modelo, capacidad) values ('Maxima', 40);
insert into trenes (modelo, capacidad) values ('Sunfire', 41);
insert into trenes (modelo, capacidad) values ('Explorer Sport Trac', 42);
insert into trenes (modelo, capacidad) values ('Xterra', 43);
insert into trenes (modelo, capacidad) values ('G', 44);
insert into trenes (modelo, capacidad) values ('X6 M', 45);
insert into trenes (modelo, capacidad) values ('Journey', 46);
insert into trenes (modelo, capacidad) values ('C-Class', 47);
insert into trenes (modelo, capacidad) values ('Mazda6', 48);
insert into trenes (modelo, capacidad) values ('5 Series', 49);
insert into trenes (modelo, capacidad) values ('Charger', 50);
insert into trenes (modelo, capacidad) values ('Prius', 51);
insert into trenes (modelo, capacidad) values ('C70', 52);
insert into trenes (modelo, capacidad) values ('X6 M', 53);
insert into trenes (modelo, capacidad) values ('XC70', 54);
insert into trenes (modelo, capacidad) values ('968', 55);
insert into trenes (modelo, capacidad) values ('Concorde', 56);
insert into trenes (modelo, capacidad) values ('900', 57);
insert into trenes (modelo, capacidad) values ('E-Series', 58);
insert into trenes (modelo, capacidad) values ('Rapide', 59);
insert into trenes (modelo, capacidad) values ('Q', 60);
insert into trenes (modelo, capacidad) values ('Sportvan G30', 61);
insert into trenes (modelo, capacidad) values ('M-Class', 62);
insert into trenes (modelo, capacidad) values ('300M', 63);
insert into trenes (modelo, capacidad) values ('S4', 64);
insert into trenes (modelo, capacidad) values ('Contour', 65);
insert into trenes (modelo, capacidad) values ('Eclipse', 66);
insert into trenes (modelo, capacidad) values ('PT Cruiser', 67);
insert into trenes (modelo, capacidad) values ('Grand Am', 68);
insert into trenes (modelo, capacidad) values ('MKX', 69);
insert into trenes (modelo, capacidad) values ('Odyssey', 70);
insert into trenes (modelo, capacidad) values ('MKX', 71);
insert into trenes (modelo, capacidad) values ('Century', 72);
insert into trenes (modelo, capacidad) values ('Silverado', 73);
insert into trenes (modelo, capacidad) values ('928', 74);
insert into trenes (modelo, capacidad) values ('SL-Class', 75);
insert into trenes (modelo, capacidad) values ('Swift', 76);
insert into trenes (modelo, capacidad) values ('Safari', 77);
insert into trenes (modelo, capacidad) values ('Boxster', 78);
insert into trenes (modelo, capacidad) values ('Sable', 79);
insert into trenes (modelo, capacidad) values ('Swift', 80);
insert into trenes (modelo, capacidad) values ('Tredia', 81);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 82);
insert into trenes (modelo, capacidad) values ('Grand Prix', 83);
insert into trenes (modelo, capacidad) values ('Sorento', 84);
insert into trenes (modelo, capacidad) values ('Legacy', 85);
insert into trenes (modelo, capacidad) values ('Escalade EXT', 86);
insert into trenes (modelo, capacidad) values ('Prizm', 87);
insert into trenes (modelo, capacidad) values ('Villager', 88);
insert into trenes (modelo, capacidad) values ('Accord', 89);
insert into trenes (modelo, capacidad) values ('Ascender', 90);
insert into trenes (modelo, capacidad) values ('Sierra 3500', 91);
insert into trenes (modelo, capacidad) values ('ES', 92);
insert into trenes (modelo, capacidad) values ('Jimmy', 93);
insert into trenes (modelo, capacidad) values ('Nitro', 94);
insert into trenes (modelo, capacidad) values ('Crown Victoria', 95);
insert into trenes (modelo, capacidad) values ('Insight', 96);
insert into trenes (modelo, capacidad) values ('900', 97);
insert into trenes (modelo, capacidad) values ('Eclipse', 98);
insert into trenes (modelo, capacidad) values ('CR-V', 99);
insert into trenes (modelo, capacidad) values ('Probe', 100);
insert into trenes (modelo, capacidad) values ('S10', 101);
insert into trenes (modelo, capacidad) values ('Tempo', 102);
insert into trenes (modelo, capacidad) values ('C-Class', 103);
insert into trenes (modelo, capacidad) values ('Escalade EXT', 104);
insert into trenes (modelo, capacidad) values ('Outlook', 105);
insert into trenes (modelo, capacidad) values ('Hombre', 106);
insert into trenes (modelo, capacidad) values ('Trans Sport', 107);
insert into trenes (modelo, capacidad) values ('Grand Prix', 108);
insert into trenes (modelo, capacidad) values ('CLS-Class', 109);
insert into trenes (modelo, capacidad) values ('Challenger', 110);
insert into trenes (modelo, capacidad) values ('Wrangler', 111);
insert into trenes (modelo, capacidad) values ('1 Series', 112);
insert into trenes (modelo, capacidad) values ('Solara', 113);
insert into trenes (modelo, capacidad) values ('Vibe', 114);
insert into trenes (modelo, capacidad) values ('Aveo', 115);
insert into trenes (modelo, capacidad) values ('Crown Victoria', 116);
insert into trenes (modelo, capacidad) values ('Versa', 117);
insert into trenes (modelo, capacidad) values ('Truck', 118);
insert into trenes (modelo, capacidad) values ('750', 119);
insert into trenes (modelo, capacidad) values ('Impala', 120);
insert into trenes (modelo, capacidad) values ('Express 1500', 121);
insert into trenes (modelo, capacidad) values ('Golf', 122);
insert into trenes (modelo, capacidad) values ('5 Series', 123);
insert into trenes (modelo, capacidad) values ('TT', 124);
insert into trenes (modelo, capacidad) values ('V90', 125);
insert into trenes (modelo, capacidad) values ('Charger', 126);
insert into trenes (modelo, capacidad) values ('Leone', 127);
insert into trenes (modelo, capacidad) values ('M', 128);
insert into trenes (modelo, capacidad) values ('Venture', 129);
insert into trenes (modelo, capacidad) values ('Sedona', 130);
insert into trenes (modelo, capacidad) values ('Concorde', 131);
insert into trenes (modelo, capacidad) values ('Golf', 132);
insert into trenes (modelo, capacidad) values ('GL-Class', 133);
insert into trenes (modelo, capacidad) values ('C30', 134);
insert into trenes (modelo, capacidad) values ('Type 2', 135);
insert into trenes (modelo, capacidad) values ('Accord', 136);
insert into trenes (modelo, capacidad) values ('Monterey', 137);
insert into trenes (modelo, capacidad) values ('GTI', 138);
insert into trenes (modelo, capacidad) values ('SLK-Class', 139);
insert into trenes (modelo, capacidad) values ('Mustang', 140);
insert into trenes (modelo, capacidad) values ('Corolla', 141);
insert into trenes (modelo, capacidad) values ('Corvette', 142);
insert into trenes (modelo, capacidad) values ('Colt Vista', 143);
insert into trenes (modelo, capacidad) values ('Sierra 1500', 144);
insert into trenes (modelo, capacidad) values ('Skyhawk', 145);
insert into trenes (modelo, capacidad) values ('Mazda3', 146);
insert into trenes (modelo, capacidad) values ('Rendezvous', 147);
insert into trenes (modelo, capacidad) values ('X6 M', 148);
insert into trenes (modelo, capacidad) values ('Range Rover', 149);
insert into trenes (modelo, capacidad) values ('Ranger', 150);
insert into trenes (modelo, capacidad) values ('Malibu', 151);
insert into trenes (modelo, capacidad) values ('Sonata', 152);
insert into trenes (modelo, capacidad) values ('F350', 153);
insert into trenes (modelo, capacidad) values ('Sequoia', 154);
insert into trenes (modelo, capacidad) values ('3 Series', 155);
insert into trenes (modelo, capacidad) values ('Fleetwood', 156);
insert into trenes (modelo, capacidad) values ('Sierra Denali', 157);
insert into trenes (modelo, capacidad) values ('Aventador', 158);
insert into trenes (modelo, capacidad) values ('Montero', 159);
insert into trenes (modelo, capacidad) values ('Escort', 160);
insert into trenes (modelo, capacidad) values ('Sportage', 161);
insert into trenes (modelo, capacidad) values ('Countach', 162);
insert into trenes (modelo, capacidad) values ('300M', 163);
insert into trenes (modelo, capacidad) values ('Prius c', 164);
insert into trenes (modelo, capacidad) values ('Cirrus', 165);
insert into trenes (modelo, capacidad) values ('Elan', 166);
insert into trenes (modelo, capacidad) values ('G-Class', 167);
insert into trenes (modelo, capacidad) values ('Esprit', 168);
insert into trenes (modelo, capacidad) values ('Azure', 169);
insert into trenes (modelo, capacidad) values ('Echo', 170);
insert into trenes (modelo, capacidad) values ('Q', 171);
insert into trenes (modelo, capacidad) values ('Range Rover Sport', 172);
insert into trenes (modelo, capacidad) values ('Grand Am', 173);
insert into trenes (modelo, capacidad) values ('VUE', 174);
insert into trenes (modelo, capacidad) values ('Tribute', 175);
insert into trenes (modelo, capacidad) values ('X-Type', 176);
insert into trenes (modelo, capacidad) values ('STS-V', 177);
insert into trenes (modelo, capacidad) values ('SL-Class', 178);
insert into trenes (modelo, capacidad) values ('300C', 179);
insert into trenes (modelo, capacidad) values ('4000', 180);
insert into trenes (modelo, capacidad) values ('Festiva', 181);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 182);
insert into trenes (modelo, capacidad) values ('Veracruz', 183);
insert into trenes (modelo, capacidad) values ('Sundance', 184);
insert into trenes (modelo, capacidad) values ('Skylark', 185);
insert into trenes (modelo, capacidad) values ('Rabbit', 186);
insert into trenes (modelo, capacidad) values ('XC70', 187);
insert into trenes (modelo, capacidad) values ('Country', 188);
insert into trenes (modelo, capacidad) values ('Ram Wagon B150', 189);
insert into trenes (modelo, capacidad) values ('Sunfire', 190);
insert into trenes (modelo, capacidad) values ('X5', 191);
insert into trenes (modelo, capacidad) values ('Sidekick', 192);
insert into trenes (modelo, capacidad) values ('Odyssey', 193);
insert into trenes (modelo, capacidad) values ('Impreza', 194);
insert into trenes (modelo, capacidad) values ('Canyon', 195);
insert into trenes (modelo, capacidad) values ('Vision', 196);
insert into trenes (modelo, capacidad) values ('Century', 197);
insert into trenes (modelo, capacidad) values ('Explorer', 198);
insert into trenes (modelo, capacidad) values ('CT', 199);
insert into trenes (modelo, capacidad) values ('Scoupe', 200);
insert into trenes (modelo, capacidad) values ('Sierra 2500', 201);
insert into trenes (modelo, capacidad) values ('Regal', 202);
insert into trenes (modelo, capacidad) values ('Sonoma', 203);
insert into trenes (modelo, capacidad) values ('Continental', 204);
insert into trenes (modelo, capacidad) values ('DB9', 205);
insert into trenes (modelo, capacidad) values ('Navajo', 206);
insert into trenes (modelo, capacidad) values ('Savana 3500', 207);
insert into trenes (modelo, capacidad) values ('Expedition', 208);
insert into trenes (modelo, capacidad) values ('Grand Caravan', 209);
insert into trenes (modelo, capacidad) values ('CLS-Class', 210);
insert into trenes (modelo, capacidad) values ('QX', 211);
insert into trenes (modelo, capacidad) values ('Neon', 212);
insert into trenes (modelo, capacidad) values ('CX-9', 213);
insert into trenes (modelo, capacidad) values ('Solstice', 214);
insert into trenes (modelo, capacidad) values ('Taurus', 215);
insert into trenes (modelo, capacidad) values ('Ram Wagon B150', 216);
insert into trenes (modelo, capacidad) values ('GTI', 217);
insert into trenes (modelo, capacidad) values ('Courier', 218);
insert into trenes (modelo, capacidad) values ('LS', 219);
insert into trenes (modelo, capacidad) values ('Bronco', 220);
insert into trenes (modelo, capacidad) values ('Mazdaspeed 3', 221);
insert into trenes (modelo, capacidad) values ('Lumina APV', 222);
insert into trenes (modelo, capacidad) values ('Tahoe', 223);
insert into trenes (modelo, capacidad) values ('Flex', 224);
insert into trenes (modelo, capacidad) values ('GTO', 225);
insert into trenes (modelo, capacidad) values ('E250', 226);
insert into trenes (modelo, capacidad) values ('Passat', 227);
insert into trenes (modelo, capacidad) values ('Tracer', 228);
insert into trenes (modelo, capacidad) values ('Seville', 229);
insert into trenes (modelo, capacidad) values ('Crossfire', 230);
insert into trenes (modelo, capacidad) values ('Diablo', 231);
insert into trenes (modelo, capacidad) values ('Grand Voyager', 232);
insert into trenes (modelo, capacidad) values ('Escalade', 233);
insert into trenes (modelo, capacidad) values ('240SX', 234);
insert into trenes (modelo, capacidad) values ('Liberty', 235);
insert into trenes (modelo, capacidad) values ('Tercel', 236);
insert into trenes (modelo, capacidad) values ('SJ', 237);
insert into trenes (modelo, capacidad) values ('E350', 238);
insert into trenes (modelo, capacidad) values ('Sienna', 239);
insert into trenes (modelo, capacidad) values ('Galant', 240);
insert into trenes (modelo, capacidad) values ('MKS', 241);
insert into trenes (modelo, capacidad) values ('Express 3500', 242);
insert into trenes (modelo, capacidad) values ('900', 243);
insert into trenes (modelo, capacidad) values ('Mountaineer', 244);
insert into trenes (modelo, capacidad) values ('Rondo', 245);
insert into trenes (modelo, capacidad) values ('Firebird', 246);
insert into trenes (modelo, capacidad) values ('Lucerne', 247);
insert into trenes (modelo, capacidad) values ('APV', 248);
insert into trenes (modelo, capacidad) values ('GX', 249);
insert into trenes (modelo, capacidad) values ('Ram 2500', 250);
insert into trenes (modelo, capacidad) values ('Achieva', 251);
insert into trenes (modelo, capacidad) values ('Cavalier', 252);
insert into trenes (modelo, capacidad) values ('Ram 2500', 253);
insert into trenes (modelo, capacidad) values ('Discovery', 254);
insert into trenes (modelo, capacidad) values ('Freestar', 255);
insert into trenes (modelo, capacidad) values ('Solara', 256);
insert into trenes (modelo, capacidad) values ('Viper', 257);
insert into trenes (modelo, capacidad) values ('Ram 2500', 258);
insert into trenes (modelo, capacidad) values ('Bravada', 259);
insert into trenes (modelo, capacidad) values ('Bonneville', 260);
insert into trenes (modelo, capacidad) values ('XLR', 261);
insert into trenes (modelo, capacidad) values ('SC', 262);
insert into trenes (modelo, capacidad) values ('Safari', 263);
insert into trenes (modelo, capacidad) values ('X5', 264);
insert into trenes (modelo, capacidad) values ('Mini', 265);
insert into trenes (modelo, capacidad) values ('Vision', 266);
insert into trenes (modelo, capacidad) values ('Rio', 267);
insert into trenes (modelo, capacidad) values ('Xterra', 268);
insert into trenes (modelo, capacidad) values ('B2500', 269);
insert into trenes (modelo, capacidad) values ('Capri', 270);
insert into trenes (modelo, capacidad) values ('Camaro', 271);
insert into trenes (modelo, capacidad) values ('GT-R', 272);
insert into trenes (modelo, capacidad) values ('Sidekick', 273);
insert into trenes (modelo, capacidad) values ('DeVille', 274);
insert into trenes (modelo, capacidad) values ('Rally Wagon G3500', 275);
insert into trenes (modelo, capacidad) values ('Grand Prix', 276);
insert into trenes (modelo, capacidad) values ('Silhouette', 277);
insert into trenes (modelo, capacidad) values ('ZX2', 278);
insert into trenes (modelo, capacidad) values ('xD', 279);
insert into trenes (modelo, capacidad) values ('Daewoo Lacetti', 280);
insert into trenes (modelo, capacidad) values ('Grand Marquis', 281);
insert into trenes (modelo, capacidad) values ('Town & Country', 282);
insert into trenes (modelo, capacidad) values ('IS', 283);
insert into trenes (modelo, capacidad) values ('Elan', 284);
insert into trenes (modelo, capacidad) values ('GS', 285);
insert into trenes (modelo, capacidad) values ('Taurus', 286);
insert into trenes (modelo, capacidad) values ('Murano', 287);
insert into trenes (modelo, capacidad) values ('Sonata', 288);
insert into trenes (modelo, capacidad) values ('Town Car', 289);
insert into trenes (modelo, capacidad) values ('3500', 290);
insert into trenes (modelo, capacidad) values ('Transit Connect', 291);
insert into trenes (modelo, capacidad) values ('S-Type', 292);
insert into trenes (modelo, capacidad) values ('Sunfire', 293);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 294);
insert into trenes (modelo, capacidad) values ('Grand Prix', 295);
insert into trenes (modelo, capacidad) values ('Yukon', 296);
insert into trenes (modelo, capacidad) values ('9-5', 297);
insert into trenes (modelo, capacidad) values ('C70', 298);
insert into trenes (modelo, capacidad) values ('ES', 299);
insert into trenes (modelo, capacidad) values ('Town Car', 300);
insert into trenes (modelo, capacidad) values ('Miata MX-5', 301);
insert into trenes (modelo, capacidad) values ('Jimmy', 302);
insert into trenes (modelo, capacidad) values ('NSX', 303);
insert into trenes (modelo, capacidad) values ('CX-9', 304);
insert into trenes (modelo, capacidad) values ('Torrent', 305);
insert into trenes (modelo, capacidad) values ('LeMans', 306);
insert into trenes (modelo, capacidad) values ('Durango', 307);
insert into trenes (modelo, capacidad) values ('Explorer', 308);
insert into trenes (modelo, capacidad) values ('Tahoe', 309);
insert into trenes (modelo, capacidad) values ('Sonata', 310);
insert into trenes (modelo, capacidad) values ('Eclipse', 311);
insert into trenes (modelo, capacidad) values ('New Beetle', 312);
insert into trenes (modelo, capacidad) values ('Probe', 313);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 314);
insert into trenes (modelo, capacidad) values ('SL-Class', 315);
insert into trenes (modelo, capacidad) values ('Starion', 316);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 317);
insert into trenes (modelo, capacidad) values ('Ram 3500', 318);
insert into trenes (modelo, capacidad) values ('V8 Vantage', 319);
insert into trenes (modelo, capacidad) values ('RAV4', 320);
insert into trenes (modelo, capacidad) values ('Galant', 321);
insert into trenes (modelo, capacidad) values ('Civic GX', 322);
insert into trenes (modelo, capacidad) values ('Jetta', 323);
insert into trenes (modelo, capacidad) values ('Yukon XL 1500', 324);
insert into trenes (modelo, capacidad) values ('Yukon XL 1500', 325);
insert into trenes (modelo, capacidad) values ('Bonneville', 326);
insert into trenes (modelo, capacidad) values ('3500', 327);
insert into trenes (modelo, capacidad) values ('Legacy', 328);
insert into trenes (modelo, capacidad) values ('Cayenne', 329);
insert into trenes (modelo, capacidad) values ('Suburban', 330);
insert into trenes (modelo, capacidad) values ('MKX', 331);
insert into trenes (modelo, capacidad) values ('Contour', 332);
insert into trenes (modelo, capacidad) values ('Cirrus', 333);
insert into trenes (modelo, capacidad) values ('LTD', 334);
insert into trenes (modelo, capacidad) values ('B-Series', 335);
insert into trenes (modelo, capacidad) values ('Touareg', 336);
insert into trenes (modelo, capacidad) values ('Esprit', 337);
insert into trenes (modelo, capacidad) values ('Club Wagon', 338);
insert into trenes (modelo, capacidad) values ('S60', 339);
insert into trenes (modelo, capacidad) values ('Econoline E150', 340);
insert into trenes (modelo, capacidad) values ('TL', 341);
insert into trenes (modelo, capacidad) values ('Veyron', 342);
insert into trenes (modelo, capacidad) values ('TT', 343);
insert into trenes (modelo, capacidad) values ('Sportvan G30', 344);
insert into trenes (modelo, capacidad) values ('Enclave', 345);
insert into trenes (modelo, capacidad) values ('CTS-V', 346);
insert into trenes (modelo, capacidad) values ('Cavalier', 347);
insert into trenes (modelo, capacidad) values ('Sentra', 348);
insert into trenes (modelo, capacidad) values ('Avalanche', 349);
insert into trenes (modelo, capacidad) values ('LS', 350);
insert into trenes (modelo, capacidad) values ('Corvette', 351);
insert into trenes (modelo, capacidad) values ('S6', 352);
insert into trenes (modelo, capacidad) values ('Titan', 353);
insert into trenes (modelo, capacidad) values ('Sky', 354);
insert into trenes (modelo, capacidad) values ('Econoline E150', 355);
insert into trenes (modelo, capacidad) values ('Bronco', 356);
insert into trenes (modelo, capacidad) values ('Sonoma Club Coupe', 357);
insert into trenes (modelo, capacidad) values ('xB', 358);
insert into trenes (modelo, capacidad) values ('Truck', 359);
insert into trenes (modelo, capacidad) values ('F450', 360);
insert into trenes (modelo, capacidad) values ('3500', 361);
insert into trenes (modelo, capacidad) values ('Freelander', 362);
insert into trenes (modelo, capacidad) values ('Crown Victoria', 363);
insert into trenes (modelo, capacidad) values ('Esprit', 364);
insert into trenes (modelo, capacidad) values ('Odyssey', 365);
insert into trenes (modelo, capacidad) values ('Civic', 366);
insert into trenes (modelo, capacidad) values ('M6', 367);
insert into trenes (modelo, capacidad) values ('Century', 368);
insert into trenes (modelo, capacidad) values ('Corvette', 369);
insert into trenes (modelo, capacidad) values ('F-Series', 370);
insert into trenes (modelo, capacidad) values ('Navigator', 371);
insert into trenes (modelo, capacidad) values ('M', 372);
insert into trenes (modelo, capacidad) values ('Yukon', 373);
insert into trenes (modelo, capacidad) values ('3 Series', 374);
insert into trenes (modelo, capacidad) values ('240SX', 375);
insert into trenes (modelo, capacidad) values ('Grand Marquis', 376);
insert into trenes (modelo, capacidad) values ('Liberty', 377);
insert into trenes (modelo, capacidad) values ('Mustang', 378);
insert into trenes (modelo, capacidad) values ('Acadia', 379);
insert into trenes (modelo, capacidad) values ('2500', 380);
insert into trenes (modelo, capacidad) values ('612 Scaglietti', 381);
insert into trenes (modelo, capacidad) values ('Sentra', 382);
insert into trenes (modelo, capacidad) values ('Vitara', 383);
insert into trenes (modelo, capacidad) values ('H1', 384);
insert into trenes (modelo, capacidad) values ('E250', 385);
insert into trenes (modelo, capacidad) values ('MX-6', 386);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 387);
insert into trenes (modelo, capacidad) values ('Prius', 388);
insert into trenes (modelo, capacidad) values ('Express 1500', 389);
insert into trenes (modelo, capacidad) values ('Express 2500', 390);
insert into trenes (modelo, capacidad) values ('i-Series', 391);
insert into trenes (modelo, capacidad) values ('Millenia', 392);
insert into trenes (modelo, capacidad) values ('Capri', 393);
insert into trenes (modelo, capacidad) values ('Lancer Evolution', 394);
insert into trenes (modelo, capacidad) values ('Regal', 395);
insert into trenes (modelo, capacidad) values ('DeVille', 396);
insert into trenes (modelo, capacidad) values ('Sedona', 397);
insert into trenes (modelo, capacidad) values ('Elise', 398);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 399);
insert into trenes (modelo, capacidad) values ('Civic', 400);
insert into trenes (modelo, capacidad) values ('SC', 401);
insert into trenes (modelo, capacidad) values ('HS', 402);
insert into trenes (modelo, capacidad) values ('Bravada', 403);
insert into trenes (modelo, capacidad) values ('Thunderbird', 404);
insert into trenes (modelo, capacidad) values ('Maxima', 405);
insert into trenes (modelo, capacidad) values ('Diablo', 406);
insert into trenes (modelo, capacidad) values ('V8 Vantage', 407);
insert into trenes (modelo, capacidad) values ('XJ Series', 408);
insert into trenes (modelo, capacidad) values ('MKX', 409);
insert into trenes (modelo, capacidad) values ('Starion', 410);
insert into trenes (modelo, capacidad) values ('Phantom', 411);
insert into trenes (modelo, capacidad) values ('G', 412);
insert into trenes (modelo, capacidad) values ('Challenger', 413);
insert into trenes (modelo, capacidad) values ('Venture', 414);
insert into trenes (modelo, capacidad) values ('Talon', 415);
insert into trenes (modelo, capacidad) values ('Sable', 416);
insert into trenes (modelo, capacidad) values ('Terrain', 417);
insert into trenes (modelo, capacidad) values ('IS', 418);
insert into trenes (modelo, capacidad) values ('Touareg', 419);
insert into trenes (modelo, capacidad) values ('Altima', 420);
insert into trenes (modelo, capacidad) values ('Montana SV6', 421);
insert into trenes (modelo, capacidad) values ('LHS', 422);
insert into trenes (modelo, capacidad) values ('Grand Cherokee', 423);
insert into trenes (modelo, capacidad) values ('LX', 424);
insert into trenes (modelo, capacidad) values ('Expedition EL', 425);
insert into trenes (modelo, capacidad) values ('Sable', 426);
insert into trenes (modelo, capacidad) values ('F350', 427);
insert into trenes (modelo, capacidad) values ('MGB', 428);
insert into trenes (modelo, capacidad) values ('Familia', 429);
insert into trenes (modelo, capacidad) values ('Mark LT', 430);
insert into trenes (modelo, capacidad) values ('Highlander', 431);
insert into trenes (modelo, capacidad) values ('Caprice Classic', 432);
insert into trenes (modelo, capacidad) values ('Miata MX-5', 433);
insert into trenes (modelo, capacidad) values ('Samurai', 434);
insert into trenes (modelo, capacidad) values ('Hemisfear', 435);
insert into trenes (modelo, capacidad) values ('Defender Ice Edition', 436);
insert into trenes (modelo, capacidad) values ('Element', 437);
insert into trenes (modelo, capacidad) values ('Camry', 438);
insert into trenes (modelo, capacidad) values ('Expedition', 439);
insert into trenes (modelo, capacidad) values ('New Beetle', 440);
insert into trenes (modelo, capacidad) values ('Solara', 441);
insert into trenes (modelo, capacidad) values ('Avalon', 442);
insert into trenes (modelo, capacidad) values ('CR-V', 443);
insert into trenes (modelo, capacidad) values ('Grand Marquis', 444);
insert into trenes (modelo, capacidad) values ('TrailBlazer', 445);
insert into trenes (modelo, capacidad) values ('Firebird', 446);
insert into trenes (modelo, capacidad) values ('JUKE', 447);
insert into trenes (modelo, capacidad) values ('Xterra', 448);
insert into trenes (modelo, capacidad) values ('9-5', 449);
insert into trenes (modelo, capacidad) values ('940', 450);
insert into trenes (modelo, capacidad) values ('Carens', 451);
insert into trenes (modelo, capacidad) values ('Catera', 452);
insert into trenes (modelo, capacidad) values ('T100', 453);
insert into trenes (modelo, capacidad) values ('Boxster', 454);
insert into trenes (modelo, capacidad) values ('Grand Vitara', 455);
insert into trenes (modelo, capacidad) values ('Tredia', 456);
insert into trenes (modelo, capacidad) values ('Rodeo Sport', 457);
insert into trenes (modelo, capacidad) values ('Avalon', 458);
insert into trenes (modelo, capacidad) values ('Malibu', 459);
insert into trenes (modelo, capacidad) values ('S4', 460);
insert into trenes (modelo, capacidad) values ('Tacoma Xtra', 461);
insert into trenes (modelo, capacidad) values ('CLS-Class', 462);
insert into trenes (modelo, capacidad) values ('SL-Class', 463);
insert into trenes (modelo, capacidad) values ('Legacy', 464);
insert into trenes (modelo, capacidad) values ('Impreza', 465);
insert into trenes (modelo, capacidad) values ('Outback', 466);
insert into trenes (modelo, capacidad) values ('1500', 467);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 468);
insert into trenes (modelo, capacidad) values ('PT Cruiser', 469);
insert into trenes (modelo, capacidad) values ('Range Rover Sport', 470);
insert into trenes (modelo, capacidad) values ('Cobalt SS', 471);
insert into trenes (modelo, capacidad) values ('Safari', 472);
insert into trenes (modelo, capacidad) values ('Justy', 473);
insert into trenes (modelo, capacidad) values ('Ram Van 2500', 474);
insert into trenes (modelo, capacidad) values ('Veloster', 475);
insert into trenes (modelo, capacidad) values ('Avalon', 476);
insert into trenes (modelo, capacidad) values ('Pathfinder', 477);
insert into trenes (modelo, capacidad) values ('Eldorado', 478);
insert into trenes (modelo, capacidad) values ('Yaris', 479);
insert into trenes (modelo, capacidad) values ('Leone', 480);
insert into trenes (modelo, capacidad) values ('Marauder', 481);
insert into trenes (modelo, capacidad) values ('GS', 482);
insert into trenes (modelo, capacidad) values ('Firefly', 483);
insert into trenes (modelo, capacidad) values ('Liberty', 484);
insert into trenes (modelo, capacidad) values ('Fleetwood', 485);
insert into trenes (modelo, capacidad) values ('Tempo', 486);
insert into trenes (modelo, capacidad) values ('Corolla', 487);
insert into trenes (modelo, capacidad) values ('XC60', 488);
insert into trenes (modelo, capacidad) values ('Touareg', 489);
insert into trenes (modelo, capacidad) values ('Town Car', 490);
insert into trenes (modelo, capacidad) values ('Lumina', 491);
insert into trenes (modelo, capacidad) values ('Skylark', 492);
insert into trenes (modelo, capacidad) values ('F150', 493);
insert into trenes (modelo, capacidad) values ('DTS', 494);
insert into trenes (modelo, capacidad) values ('Colt', 495);
insert into trenes (modelo, capacidad) values ('Grand Prix', 496);
insert into trenes (modelo, capacidad) values ('CL-Class', 497);
insert into trenes (modelo, capacidad) values ('Insight', 498);
insert into trenes (modelo, capacidad) values ('Vantage', 499);
insert into trenes (modelo, capacidad) values ('Highlander', 500);
insert into trenes (modelo, capacidad) values ('Impala SS', 501);
insert into trenes (modelo, capacidad) values ('Solstice', 502);
insert into trenes (modelo, capacidad) values ('Eos', 503);
insert into trenes (modelo, capacidad) values ('JUKE', 504);
insert into trenes (modelo, capacidad) values ('Ghost', 505);
insert into trenes (modelo, capacidad) values ('Yukon XL 2500', 506);
insert into trenes (modelo, capacidad) values ('C-MAX Hybrid', 507);
insert into trenes (modelo, capacidad) values ('1500', 508);
insert into trenes (modelo, capacidad) values ('Fortwo', 509);
insert into trenes (modelo, capacidad) values ('Tempo', 510);
insert into trenes (modelo, capacidad) values ('Maxima', 511);
insert into trenes (modelo, capacidad) values ('Fury', 512);
insert into trenes (modelo, capacidad) values ('1500', 513);
insert into trenes (modelo, capacidad) values ('911', 514);
insert into trenes (modelo, capacidad) values ('SJ', 515);
insert into trenes (modelo, capacidad) values ('Explorer Sport Trac', 516);
insert into trenes (modelo, capacidad) values ('S60', 517);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 518);
insert into trenes (modelo, capacidad) values ('Dakota', 519);
insert into trenes (modelo, capacidad) values ('Jetta III', 520);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 521);
insert into trenes (modelo, capacidad) values ('Express 1500', 522);
insert into trenes (modelo, capacidad) values ('G', 523);
insert into trenes (modelo, capacidad) values ('APV', 524);
insert into trenes (modelo, capacidad) values ('E-Series', 525);
insert into trenes (modelo, capacidad) values ('Cabriolet', 526);
insert into trenes (modelo, capacidad) values ('i-370', 527);
insert into trenes (modelo, capacidad) values ('Volt', 528);
insert into trenes (modelo, capacidad) values ('G', 529);
insert into trenes (modelo, capacidad) values ('Starion', 530);
insert into trenes (modelo, capacidad) values ('Santa Fe', 531);
insert into trenes (modelo, capacidad) values ('Evora', 532);
insert into trenes (modelo, capacidad) values ('RL', 533);
insert into trenes (modelo, capacidad) values ('tC', 534);
insert into trenes (modelo, capacidad) values ('Sonata', 535);
insert into trenes (modelo, capacidad) values ('FX', 536);
insert into trenes (modelo, capacidad) values ('STS-V', 537);
insert into trenes (modelo, capacidad) values ('Vanquish S', 538);
insert into trenes (modelo, capacidad) values ('Edge', 539);
insert into trenes (modelo, capacidad) values ('Grand Cherokee', 540);
insert into trenes (modelo, capacidad) values ('F-Series', 541);
insert into trenes (modelo, capacidad) values ('Mazdaspeed 3', 542);
insert into trenes (modelo, capacidad) values ('Passat', 543);
insert into trenes (modelo, capacidad) values ('Fiesta', 544);
insert into trenes (modelo, capacidad) values ('Landaulet', 545);
insert into trenes (modelo, capacidad) values ('Discovery', 546);
insert into trenes (modelo, capacidad) values ('TL', 547);
insert into trenes (modelo, capacidad) values ('Explorer', 548);
insert into trenes (modelo, capacidad) values ('Tercel', 549);
insert into trenes (modelo, capacidad) values ('XK Series', 550);
insert into trenes (modelo, capacidad) values ('Sierra 3500', 551);
insert into trenes (modelo, capacidad) values ('Forester', 552);
insert into trenes (modelo, capacidad) values ('Jetta', 553);
insert into trenes (modelo, capacidad) values ('X5', 554);
insert into trenes (modelo, capacidad) values ('H1', 555);
insert into trenes (modelo, capacidad) values ('Malibu', 556);
insert into trenes (modelo, capacidad) values ('Murano', 557);
insert into trenes (modelo, capacidad) values ('Somerset', 558);
insert into trenes (modelo, capacidad) values ('1500', 559);
insert into trenes (modelo, capacidad) values ('Prelude', 560);
insert into trenes (modelo, capacidad) values ('SC', 561);
insert into trenes (modelo, capacidad) values ('Swift', 562);
insert into trenes (modelo, capacidad) values ('Venza', 563);
insert into trenes (modelo, capacidad) values ('Beretta', 564);
insert into trenes (modelo, capacidad) values ('Tahoe', 565);
insert into trenes (modelo, capacidad) values ('Brat', 566);
insert into trenes (modelo, capacidad) values ('Esteem', 567);
insert into trenes (modelo, capacidad) values ('Grand Caravan', 568);
insert into trenes (modelo, capacidad) values ('Edge', 569);
insert into trenes (modelo, capacidad) values ('Crown Victoria', 570);
insert into trenes (modelo, capacidad) values ('Ram', 571);
insert into trenes (modelo, capacidad) values ('Crown Victoria', 572);
insert into trenes (modelo, capacidad) values ('Falcon', 573);
insert into trenes (modelo, capacidad) values ('Integra', 574);
insert into trenes (modelo, capacidad) values ('Camry', 575);
insert into trenes (modelo, capacidad) values ('Marauder', 576);
insert into trenes (modelo, capacidad) values ('B-Series', 577);
insert into trenes (modelo, capacidad) values ('Montana', 578);
insert into trenes (modelo, capacidad) values ('Grand Am', 579);
insert into trenes (modelo, capacidad) values ('A8', 580);
insert into trenes (modelo, capacidad) values ('Corolla', 581);
insert into trenes (modelo, capacidad) values ('A4', 582);
insert into trenes (modelo, capacidad) values ('A8', 583);
insert into trenes (modelo, capacidad) values ('Golf', 584);
insert into trenes (modelo, capacidad) values ('Mirage', 585);
insert into trenes (modelo, capacidad) values ('CR-V', 586);
insert into trenes (modelo, capacidad) values ('SL-Class', 587);
insert into trenes (modelo, capacidad) values ('XT', 588);
insert into trenes (modelo, capacidad) values ('Armada', 589);
insert into trenes (modelo, capacidad) values ('Monaro', 590);
insert into trenes (modelo, capacidad) values ('Dakota Club', 591);
insert into trenes (modelo, capacidad) values ('Quattroporte', 592);
insert into trenes (modelo, capacidad) values ('Ram Wagon B250', 593);
insert into trenes (modelo, capacidad) values ('Space', 594);
insert into trenes (modelo, capacidad) values ('Cutlass Supreme', 595);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 596);
insert into trenes (modelo, capacidad) values ('Z3', 597);
insert into trenes (modelo, capacidad) values ('914', 598);
insert into trenes (modelo, capacidad) values ('1500 Club Coupe', 599);
insert into trenes (modelo, capacidad) values ('7 Series', 600);
insert into trenes (modelo, capacidad) values ('Beretta', 601);
insert into trenes (modelo, capacidad) values ('Mark VIII', 602);
insert into trenes (modelo, capacidad) values ('Cherokee', 603);
insert into trenes (modelo, capacidad) values ('del Sol', 604);
insert into trenes (modelo, capacidad) values ('CR-V', 605);
insert into trenes (modelo, capacidad) values ('SLX', 606);
insert into trenes (modelo, capacidad) values ('Eldorado', 607);
insert into trenes (modelo, capacidad) values ('Silverado 2500', 608);
insert into trenes (modelo, capacidad) values ('350Z Roadster', 609);
insert into trenes (modelo, capacidad) values ('Mountaineer', 610);
insert into trenes (modelo, capacidad) values ('Protege', 611);
insert into trenes (modelo, capacidad) values ('Alero', 612);
insert into trenes (modelo, capacidad) values ('XC60', 613);
insert into trenes (modelo, capacidad) values ('G-Series G20', 614);
insert into trenes (modelo, capacidad) values ('Lucerne', 615);
insert into trenes (modelo, capacidad) values ('RX Hybrid', 616);
insert into trenes (modelo, capacidad) values ('Cavalier', 617);
insert into trenes (modelo, capacidad) values ('Ranger', 618);
insert into trenes (modelo, capacidad) values ('Q', 619);
insert into trenes (modelo, capacidad) values ('RX', 620);
insert into trenes (modelo, capacidad) values ('Regal', 621);
insert into trenes (modelo, capacidad) values ('C30', 622);
insert into trenes (modelo, capacidad) values ('SC', 623);
insert into trenes (modelo, capacidad) values ('Bonneville', 624);
insert into trenes (modelo, capacidad) values ('Town & Country', 625);
insert into trenes (modelo, capacidad) values ('Optima', 626);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 627);
insert into trenes (modelo, capacidad) values ('S40', 628);
insert into trenes (modelo, capacidad) values ('Gallardo', 629);
insert into trenes (modelo, capacidad) values ('XK Series', 630);
insert into trenes (modelo, capacidad) values ('Ranger', 631);
insert into trenes (modelo, capacidad) values ('Defender Ice Edition', 632);
insert into trenes (modelo, capacidad) values ('A4', 633);
insert into trenes (modelo, capacidad) values ('Millenia', 634);
insert into trenes (modelo, capacidad) values ('XC70', 635);
insert into trenes (modelo, capacidad) values ('Canyon', 636);
insert into trenes (modelo, capacidad) values ('Accord', 637);
insert into trenes (modelo, capacidad) values ('Torrent', 638);
insert into trenes (modelo, capacidad) values ('4Runner', 639);
insert into trenes (modelo, capacidad) values ('Tundra', 640);
insert into trenes (modelo, capacidad) values ('MKT', 641);
insert into trenes (modelo, capacidad) values ('CLK-Class', 642);
insert into trenes (modelo, capacidad) values ('924 S', 643);
insert into trenes (modelo, capacidad) values ('Neon', 644);
insert into trenes (modelo, capacidad) values ('A3', 645);
insert into trenes (modelo, capacidad) values ('Montana', 646);
insert into trenes (modelo, capacidad) values ('XK Series', 647);
insert into trenes (modelo, capacidad) values ('Montero', 648);
insert into trenes (modelo, capacidad) values ('Silverado 3500HD', 649);
insert into trenes (modelo, capacidad) values ('Tracker', 650);
insert into trenes (modelo, capacidad) values ('Bonneville', 651);
insert into trenes (modelo, capacidad) values ('Eclipse', 652);
insert into trenes (modelo, capacidad) values ('Q5', 653);
insert into trenes (modelo, capacidad) values ('Fox', 654);
insert into trenes (modelo, capacidad) values ('LS', 655);
insert into trenes (modelo, capacidad) values ('XC90', 656);
insert into trenes (modelo, capacidad) values ('PT Cruiser', 657);
insert into trenes (modelo, capacidad) values ('CX-7', 658);
insert into trenes (modelo, capacidad) values ('Fifth Ave', 659);
insert into trenes (modelo, capacidad) values ('370Z', 660);
insert into trenes (modelo, capacidad) values ('600SEL', 661);
insert into trenes (modelo, capacidad) values ('Touareg', 662);
insert into trenes (modelo, capacidad) values ('Elise', 663);
insert into trenes (modelo, capacidad) values ('Integra', 664);
insert into trenes (modelo, capacidad) values ('S10', 665);
insert into trenes (modelo, capacidad) values ('F430', 666);
insert into trenes (modelo, capacidad) values ('X-90', 667);
insert into trenes (modelo, capacidad) values ('Charger', 668);
insert into trenes (modelo, capacidad) values ('Express', 669);
insert into trenes (modelo, capacidad) values ('Tahoe', 670);
insert into trenes (modelo, capacidad) values ('G35', 671);
insert into trenes (modelo, capacidad) values ('FCX Clarity', 672);
insert into trenes (modelo, capacidad) values ('PT Cruiser', 673);
insert into trenes (modelo, capacidad) values ('Accord Crosstour', 674);
insert into trenes (modelo, capacidad) values ('Avalon', 675);
insert into trenes (modelo, capacidad) values ('9-5', 676);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 677);
insert into trenes (modelo, capacidad) values ('GTI', 678);
insert into trenes (modelo, capacidad) values ('Elantra', 679);
insert into trenes (modelo, capacidad) values ('Firebird', 680);
insert into trenes (modelo, capacidad) values ('E-Class', 681);
insert into trenes (modelo, capacidad) values ('Tercel', 682);
insert into trenes (modelo, capacidad) values ('Express 1500', 683);
insert into trenes (modelo, capacidad) values ('A8', 684);
insert into trenes (modelo, capacidad) values ('Cherokee', 685);
insert into trenes (modelo, capacidad) values ('A7', 686);
insert into trenes (modelo, capacidad) values ('Continental Mark VII', 687);
insert into trenes (modelo, capacidad) values ('Xterra', 688);
insert into trenes (modelo, capacidad) values ('Tucson', 689);
insert into trenes (modelo, capacidad) values ('Lancer', 690);
insert into trenes (modelo, capacidad) values ('CR-X', 691);
insert into trenes (modelo, capacidad) values ('Town Car', 692);
insert into trenes (modelo, capacidad) values ('Sunbird', 693);
insert into trenes (modelo, capacidad) values ('A6', 694);
insert into trenes (modelo, capacidad) values ('Pajero', 695);
insert into trenes (modelo, capacidad) values ('Yukon XL 1500', 696);
insert into trenes (modelo, capacidad) values ('Ion', 697);
insert into trenes (modelo, capacidad) values ('XC60', 698);
insert into trenes (modelo, capacidad) values ('Silverado', 699);
insert into trenes (modelo, capacidad) values ('Sidekick', 700);
insert into trenes (modelo, capacidad) values ('Sonata', 701);
insert into trenes (modelo, capacidad) values ('Sixty Special', 702);
insert into trenes (modelo, capacidad) values ('Freelander', 703);
insert into trenes (modelo, capacidad) values ('Grand Prix', 704);
insert into trenes (modelo, capacidad) values ('Versa', 705);
insert into trenes (modelo, capacidad) values ('228', 706);
insert into trenes (modelo, capacidad) values ('SLR McLaren', 707);
insert into trenes (modelo, capacidad) values ('Silverado 1500', 708);
insert into trenes (modelo, capacidad) values ('Matrix', 709);
insert into trenes (modelo, capacidad) values ('Prius', 710);
insert into trenes (modelo, capacidad) values ('xB', 711);
insert into trenes (modelo, capacidad) values ('Explorer', 712);
insert into trenes (modelo, capacidad) values ('Ram 2500', 713);
insert into trenes (modelo, capacidad) values ('300', 714);
insert into trenes (modelo, capacidad) values ('6 Series', 715);
insert into trenes (modelo, capacidad) values ('Elantra', 716);
insert into trenes (modelo, capacidad) values ('SSR', 717);
insert into trenes (modelo, capacidad) values ('SJ', 718);
insert into trenes (modelo, capacidad) values ('Mazda3', 719);
insert into trenes (modelo, capacidad) values ('Galant', 720);
insert into trenes (modelo, capacidad) values ('Defender 90', 721);
insert into trenes (modelo, capacidad) values ('Rabbit', 722);
insert into trenes (modelo, capacidad) values ('Z3', 723);
insert into trenes (modelo, capacidad) values ('Impreza', 724);
insert into trenes (modelo, capacidad) values ('Brooklands', 725);
insert into trenes (modelo, capacidad) values ('Corvette', 726);
insert into trenes (modelo, capacidad) values ('Savana 2500', 727);
insert into trenes (modelo, capacidad) values ('RAV4', 728);
insert into trenes (modelo, capacidad) values ('Silhouette', 729);
insert into trenes (modelo, capacidad) values ('DeVille', 730);
insert into trenes (modelo, capacidad) values ('TSX', 731);
insert into trenes (modelo, capacidad) values ('Venture', 732);
insert into trenes (modelo, capacidad) values ('Astro', 733);
insert into trenes (modelo, capacidad) values ('S-Series', 734);
insert into trenes (modelo, capacidad) values ('XL-7', 735);
insert into trenes (modelo, capacidad) values ('Sierra 1500', 736);
insert into trenes (modelo, capacidad) values ('Golf', 737);
insert into trenes (modelo, capacidad) values ('Sable', 738);
insert into trenes (modelo, capacidad) values ('Protege', 739);
insert into trenes (modelo, capacidad) values ('Navigator', 740);
insert into trenes (modelo, capacidad) values ('S70', 741);
insert into trenes (modelo, capacidad) values ('Lancer Evolution', 742);
insert into trenes (modelo, capacidad) values ('7 Series', 743);
insert into trenes (modelo, capacidad) values ('5 Series', 744);
insert into trenes (modelo, capacidad) values ('626', 745);
insert into trenes (modelo, capacidad) values ('Legacy', 746);
insert into trenes (modelo, capacidad) values ('Corvette', 747);
insert into trenes (modelo, capacidad) values ('Century', 748);
insert into trenes (modelo, capacidad) values ('E-Series', 749);
insert into trenes (modelo, capacidad) values ('Stealth', 750);
insert into trenes (modelo, capacidad) values ('240SX', 751);
insert into trenes (modelo, capacidad) values ('Brooklands', 752);
insert into trenes (modelo, capacidad) values ('Justy', 753);
insert into trenes (modelo, capacidad) values ('Maxima', 754);
insert into trenes (modelo, capacidad) values ('Escort', 755);
insert into trenes (modelo, capacidad) values ('Concorde', 756);
insert into trenes (modelo, capacidad) values ('M6', 757);
insert into trenes (modelo, capacidad) values ('Caprice', 758);
insert into trenes (modelo, capacidad) values ('Neon', 759);
insert into trenes (modelo, capacidad) values ('Intrepid', 760);
insert into trenes (modelo, capacidad) values ('Yukon XL 2500', 761);
insert into trenes (modelo, capacidad) values ('3500', 762);
insert into trenes (modelo, capacidad) values ('Colt Vista', 763);
insert into trenes (modelo, capacidad) values ('Altima', 764);
insert into trenes (modelo, capacidad) values ('Raider', 765);
insert into trenes (modelo, capacidad) values ('S2000', 766);
insert into trenes (modelo, capacidad) values ('Land Cruiser', 767);
insert into trenes (modelo, capacidad) values ('Express 2500', 768);
insert into trenes (modelo, capacidad) values ('MPV', 769);
insert into trenes (modelo, capacidad) values ('Escalade EXT', 770);
insert into trenes (modelo, capacidad) values ('940', 771);
insert into trenes (modelo, capacidad) values ('NSX', 772);
insert into trenes (modelo, capacidad) values ('Daewoo Lacetti', 773);
insert into trenes (modelo, capacidad) values ('5 Series', 774);
insert into trenes (modelo, capacidad) values ('Lancer', 775);
insert into trenes (modelo, capacidad) values ('Econoline E250', 776);
insert into trenes (modelo, capacidad) values ('Titan', 777);
insert into trenes (modelo, capacidad) values ('F-Series', 778);
insert into trenes (modelo, capacidad) values ('Aztek', 779);
insert into trenes (modelo, capacidad) values ('CTS', 780);
insert into trenes (modelo, capacidad) values ('Caravan', 781);
insert into trenes (modelo, capacidad) values ('Coupe Quattro', 782);
insert into trenes (modelo, capacidad) values ('400SEL', 783);
insert into trenes (modelo, capacidad) values ('Civic', 784);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 785);
insert into trenes (modelo, capacidad) values ('Envoy XL', 786);
insert into trenes (modelo, capacidad) values ('Ram Wagon B350', 787);
insert into trenes (modelo, capacidad) values ('Sierra 2500', 788);
insert into trenes (modelo, capacidad) values ('Sephia', 789);
insert into trenes (modelo, capacidad) values ('L-Series', 790);
insert into trenes (modelo, capacidad) values ('Firebird', 791);
insert into trenes (modelo, capacidad) values ('Continental Mark VII', 792);
insert into trenes (modelo, capacidad) values ('RSX', 793);
insert into trenes (modelo, capacidad) values ('D150 Club', 794);
insert into trenes (modelo, capacidad) values ('370Z', 795);
insert into trenes (modelo, capacidad) values ('ES', 796);
insert into trenes (modelo, capacidad) values ('ZDX', 797);
insert into trenes (modelo, capacidad) values ('Rainier', 798);
insert into trenes (modelo, capacidad) values ('Colorado', 799);
insert into trenes (modelo, capacidad) values ('626', 800);
insert into trenes (modelo, capacidad) values ('5000CS Quattro', 801);
insert into trenes (modelo, capacidad) values ('F-Series', 802);
insert into trenes (modelo, capacidad) values ('Ram Van 3500', 803);
insert into trenes (modelo, capacidad) values ('A6', 804);
insert into trenes (modelo, capacidad) values ('Viper', 805);
insert into trenes (modelo, capacidad) values ('Civic', 806);
insert into trenes (modelo, capacidad) values ('Range Rover Sport', 807);
insert into trenes (modelo, capacidad) values ('Type 2', 808);
insert into trenes (modelo, capacidad) values ('Century', 809);
insert into trenes (modelo, capacidad) values ('2500 Club Coupe', 810);
insert into trenes (modelo, capacidad) values ('SL-Class', 811);
insert into trenes (modelo, capacidad) values ('GTI', 812);
insert into trenes (modelo, capacidad) values ('Grand Prix', 813);
insert into trenes (modelo, capacidad) values ('Entourage', 814);
insert into trenes (modelo, capacidad) values ('Trooper', 815);
insert into trenes (modelo, capacidad) values ('Sequoia', 816);
insert into trenes (modelo, capacidad) values ('Malibu', 817);
insert into trenes (modelo, capacidad) values ('3500 Club Coupe', 818);
insert into trenes (modelo, capacidad) values ('Ram 3500', 819);
insert into trenes (modelo, capacidad) values ('CLS-Class', 820);
insert into trenes (modelo, capacidad) values ('Sidekick', 821);
insert into trenes (modelo, capacidad) values ('Capri', 822);
insert into trenes (modelo, capacidad) values ('Tracer', 823);
insert into trenes (modelo, capacidad) values ('M-Class', 824);
insert into trenes (modelo, capacidad) values ('Golf III', 825);
insert into trenes (modelo, capacidad) values ('Imperial', 826);
insert into trenes (modelo, capacidad) values ('Suburban 1500', 827);
insert into trenes (modelo, capacidad) values ('Insight', 828);
insert into trenes (modelo, capacidad) values ('M-Class', 829);
insert into trenes (modelo, capacidad) values ('80/90', 830);
insert into trenes (modelo, capacidad) values ('911', 831);
insert into trenes (modelo, capacidad) values ('Mountaineer', 832);
insert into trenes (modelo, capacidad) values ('Cavalier', 833);
insert into trenes (modelo, capacidad) values ('Sonoma', 834);
insert into trenes (modelo, capacidad) values ('Elantra', 835);
insert into trenes (modelo, capacidad) values ('Miata MX-5', 836);
insert into trenes (modelo, capacidad) values ('S60', 837);
insert into trenes (modelo, capacidad) values ('Alero', 838);
insert into trenes (modelo, capacidad) values ('Metro', 839);
insert into trenes (modelo, capacidad) values ('Esteem', 840);
insert into trenes (modelo, capacidad) values ('Escalade ESV', 841);
insert into trenes (modelo, capacidad) values ('Town Car', 842);
insert into trenes (modelo, capacidad) values ('Swift', 843);
insert into trenes (modelo, capacidad) values ('Continental Mark VII', 844);
insert into trenes (modelo, capacidad) values ('Firebird', 845);
insert into trenes (modelo, capacidad) values ('Avalon', 846);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 847);
insert into trenes (modelo, capacidad) values ('Prowler', 848);
insert into trenes (modelo, capacidad) values ('Monterey', 849);
insert into trenes (modelo, capacidad) values ('Park Avenue', 850);
insert into trenes (modelo, capacidad) values ('Azure T', 851);
insert into trenes (modelo, capacidad) values ('600SL', 852);
insert into trenes (modelo, capacidad) values ('Swift', 853);
insert into trenes (modelo, capacidad) values ('L-Series', 854);
insert into trenes (modelo, capacidad) values ('Mountaineer', 855);
insert into trenes (modelo, capacidad) values ('1500 Club Coupe', 856);
insert into trenes (modelo, capacidad) values ('Avanti', 857);
insert into trenes (modelo, capacidad) values ('S10', 858);
insert into trenes (modelo, capacidad) values ('Voyager', 859);
insert into trenes (modelo, capacidad) values ('Gallardo', 860);
insert into trenes (modelo, capacidad) values ('Legacy', 861);
insert into trenes (modelo, capacidad) values ('Diablo', 862);
insert into trenes (modelo, capacidad) values ('GLC', 863);
insert into trenes (modelo, capacidad) values ('Sebring', 864);
insert into trenes (modelo, capacidad) values ('E350', 865);
insert into trenes (modelo, capacidad) values ('LS', 866);
insert into trenes (modelo, capacidad) values ('Frontier', 867);
insert into trenes (modelo, capacidad) values ('Esperante', 868);
insert into trenes (modelo, capacidad) values ('Rendezvous', 869);
insert into trenes (modelo, capacidad) values ('Solara', 870);
insert into trenes (modelo, capacidad) values ('S40', 871);
insert into trenes (modelo, capacidad) values ('Escape', 872);
insert into trenes (modelo, capacidad) values ('Cavalier', 873);
insert into trenes (modelo, capacidad) values ('TL', 874);
insert into trenes (modelo, capacidad) values ('CR-X', 875);
insert into trenes (modelo, capacidad) values ('Lancer Evolution', 876);
insert into trenes (modelo, capacidad) values ('MR2', 877);
insert into trenes (modelo, capacidad) values ('Festiva', 878);
insert into trenes (modelo, capacidad) values ('Bonneville', 879);
insert into trenes (modelo, capacidad) values ('Titan', 880);
insert into trenes (modelo, capacidad) values ('Ascender', 881);
insert into trenes (modelo, capacidad) values ('Relay', 882);
insert into trenes (modelo, capacidad) values ('Sprinter', 883);
insert into trenes (modelo, capacidad) values ('Bravada', 884);
insert into trenes (modelo, capacidad) values ('Taurus', 885);
insert into trenes (modelo, capacidad) values ('Yukon XL 2500', 886);
insert into trenes (modelo, capacidad) values ('Escort', 887);
insert into trenes (modelo, capacidad) values ('Range Rover', 888);
insert into trenes (modelo, capacidad) values ('Regal', 889);
insert into trenes (modelo, capacidad) values ('Silverado 3500', 890);
insert into trenes (modelo, capacidad) values ('E250', 891);
insert into trenes (modelo, capacidad) values ('Miata MX-5', 892);
insert into trenes (modelo, capacidad) values ('Laser', 893);
insert into trenes (modelo, capacidad) values ('Esteem', 894);
insert into trenes (modelo, capacidad) values ('9-4X', 895);
insert into trenes (modelo, capacidad) values ('Aerostar', 896);
insert into trenes (modelo, capacidad) values ('Celica', 897);
insert into trenes (modelo, capacidad) values ('tC', 898);
insert into trenes (modelo, capacidad) values ('350Z', 899);
insert into trenes (modelo, capacidad) values ('Pathfinder', 900);
insert into trenes (modelo, capacidad) values ('Legend', 901);
insert into trenes (modelo, capacidad) values ('Silverado 2500', 902);
insert into trenes (modelo, capacidad) values ('Sonoma', 903);
insert into trenes (modelo, capacidad) values ('Cayenne', 904);
insert into trenes (modelo, capacidad) values ('del Sol', 905);
insert into trenes (modelo, capacidad) values ('Mirage', 906);
insert into trenes (modelo, capacidad) values ('W201', 907);
insert into trenes (modelo, capacidad) values ('XC90', 908);
insert into trenes (modelo, capacidad) values ('IPL G', 909);
insert into trenes (modelo, capacidad) values ('Cruze', 910);
insert into trenes (modelo, capacidad) values ('Jetta', 911);
insert into trenes (modelo, capacidad) values ('Sonata', 912);
insert into trenes (modelo, capacidad) values ('Elantra', 913);
insert into trenes (modelo, capacidad) values ('Durango', 914);
insert into trenes (modelo, capacidad) values ('Impala', 915);
insert into trenes (modelo, capacidad) values ('Passport', 916);
insert into trenes (modelo, capacidad) values ('Sequoia', 917);
insert into trenes (modelo, capacidad) values ('Avalon', 918);
insert into trenes (modelo, capacidad) values ('Elantra', 919);
insert into trenes (modelo, capacidad) values ('Montero', 920);
insert into trenes (modelo, capacidad) values ('Optima', 921);
insert into trenes (modelo, capacidad) values ('Camaro', 922);
insert into trenes (modelo, capacidad) values ('Freestyle', 923);
insert into trenes (modelo, capacidad) values ('Ram 2500', 924);
insert into trenes (modelo, capacidad) values ('CLK-Class', 925);
insert into trenes (modelo, capacidad) values ('Roadster', 926);
insert into trenes (modelo, capacidad) values ('Ranger', 927);
insert into trenes (modelo, capacidad) values ('Camaro', 928);
insert into trenes (modelo, capacidad) values ('F350', 929);
insert into trenes (modelo, capacidad) values ('LHS', 930);
insert into trenes (modelo, capacidad) values ('Civic', 931);
insert into trenes (modelo, capacidad) values ('Allante', 932);
insert into trenes (modelo, capacidad) values ('XL-7', 933);
insert into trenes (modelo, capacidad) values ('Silhouette', 934);
insert into trenes (modelo, capacidad) values ('Continental Mark VII', 935);
insert into trenes (modelo, capacidad) values ('Astro', 936);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 937);
insert into trenes (modelo, capacidad) values ('300C', 938);
insert into trenes (modelo, capacidad) values ('Sierra 1500', 939);
insert into trenes (modelo, capacidad) values ('900', 940);
insert into trenes (modelo, capacidad) values ('A8', 941);
insert into trenes (modelo, capacidad) values ('F-Series', 942);
insert into trenes (modelo, capacidad) values ('Cherokee', 943);
insert into trenes (modelo, capacidad) values ('Avalon', 944);
insert into trenes (modelo, capacidad) values ('911', 945);
insert into trenes (modelo, capacidad) values ('xB', 946);
insert into trenes (modelo, capacidad) values ('C-Class', 947);
insert into trenes (modelo, capacidad) values ('Tundra', 948);
insert into trenes (modelo, capacidad) values ('Sonoma Club Coupe', 949);
insert into trenes (modelo, capacidad) values ('Eurovan', 950);
insert into trenes (modelo, capacidad) values ('Daewoo Lacetti', 951);
insert into trenes (modelo, capacidad) values ('Laser', 952);
insert into trenes (modelo, capacidad) values ('Highlander', 953);
insert into trenes (modelo, capacidad) values ('Mini Cooper S', 954);
insert into trenes (modelo, capacidad) values ('Econoline E250', 955);
insert into trenes (modelo, capacidad) values ('Explorer Sport Trac', 956);
insert into trenes (modelo, capacidad) values ('Malibu', 957);
insert into trenes (modelo, capacidad) values ('IS', 958);
insert into trenes (modelo, capacidad) values ('Truck', 959);
insert into trenes (modelo, capacidad) values ('Charger', 960);
insert into trenes (modelo, capacidad) values ('Montero', 961);
insert into trenes (modelo, capacidad) values ('Passat', 962);
insert into trenes (modelo, capacidad) values ('300', 963);
insert into trenes (modelo, capacidad) values ('Pathfinder', 964);
insert into trenes (modelo, capacidad) values ('Alcyone SVX', 965);
insert into trenes (modelo, capacidad) values ('VehiCROSS', 966);
insert into trenes (modelo, capacidad) values ('Traverse', 967);
insert into trenes (modelo, capacidad) values ('Sonata', 968);
insert into trenes (modelo, capacidad) values ('SLS-Class', 969);
insert into trenes (modelo, capacidad) values ('Rendezvous', 970);
insert into trenes (modelo, capacidad) values ('Rio', 971);
insert into trenes (modelo, capacidad) values ('Savana 2500', 972);
insert into trenes (modelo, capacidad) values ('Ram 2500 Club', 973);
insert into trenes (modelo, capacidad) values ('Forenza', 974);
insert into trenes (modelo, capacidad) values ('Rogue', 975);
insert into trenes (modelo, capacidad) values ('Hombre', 976);
insert into trenes (modelo, capacidad) values ('530', 977);
insert into trenes (modelo, capacidad) values ('M3', 978);
insert into trenes (modelo, capacidad) values ('Santa Fe', 979);
insert into trenes (modelo, capacidad) values ('Silverado', 980);
insert into trenes (modelo, capacidad) values ('Ram 2500', 981);
insert into trenes (modelo, capacidad) values ('Veracruz', 982);
insert into trenes (modelo, capacidad) values ('Sable', 983);
insert into trenes (modelo, capacidad) values ('Monte Carlo', 984);
insert into trenes (modelo, capacidad) values ('RX-7', 985);
insert into trenes (modelo, capacidad) values ('Eclipse', 986);
insert into trenes (modelo, capacidad) values ('Ram Van 2500', 987);
insert into trenes (modelo, capacidad) values ('S60', 988);
insert into trenes (modelo, capacidad) values ('Navigator L', 989);
insert into trenes (modelo, capacidad) values ('200SX', 990);
insert into trenes (modelo, capacidad) values ('V40', 991);
insert into trenes (modelo, capacidad) values ('Ram Van 3500', 992);
insert into trenes (modelo, capacidad) values ('LR4', 993);
insert into trenes (modelo, capacidad) values ('B2500', 994);
insert into trenes (modelo, capacidad) values ('SL-Class', 995);
insert into trenes (modelo, capacidad) values ('Sunbird', 996);
insert into trenes (modelo, capacidad) values ('Celica', 997);
insert into trenes (modelo, capacidad) values ('M Roadster', 998);
insert into trenes (modelo, capacidad) values ('E-Class', 999);
insert into trenes (modelo, capacidad) values ('Cherokee', 1000);
